"""Generate docs/permissions-matrix.md and docs/api.md from the running code.

    python scripts/generate_ops_docs.py

Both files are derived artefacts: edit the permission registry or the routes,
then re-run this script.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from asme import create_app  # noqa: E402
from asme.ops import permissions as registry  # noqa: E402

SCOPE_ABBR = {"chapter": "C", "project": "P", "team": "T", "assigned": "A", "own": "O"}


def permissions_matrix() -> str:
    roles = registry.SYSTEM_ROLES
    lines = [
        "# Permissions matrix",
        "",
        "Generated by `python scripts/generate_ops_docs.py` from `asme/ops/permissions.py`. Do not edit by hand.",
        "",
        "Scopes: **C** chapter-wide · **P** projects the user is a member of · **T** teams the user leads (read keys: is a member of) · **A** records assigned to the user or their teams · **O** records the user created. Legacy roles map at first sign-in: `admin → chapter_admin`, `team_leader → team_lead`, `member → full_member`.",
        "",
        "| Permission | " + " | ".join(r["name"] for r in roles) + " |",
        "|---|" + "|".join(["---"] * len(roles)) + "|",
    ]
    for key, description in registry.PERMISSIONS.items():
        cells = []
        for role in roles:
            scope = registry.DEFAULT_GRANTS.get(role["key"], {}).get(key)
            cells.append(SCOPE_ABBR[scope] if scope else "")
        lines.append(f"| `{key}`<br><small>{description}</small> | " + " | ".join(cells) + " |")
    lines += ["", "## Roles", ""]
    for role in roles:
        lines.append(f"- **{role['name']}** (`{role['key']}`): {role['description']}")
    return "\n".join(lines) + "\n"


def api_reference(app) -> str:
    rows = []
    for rule in app.url_map.iter_rules():
        if not rule.rule.startswith("/api/v1/") or rule.endpoint.startswith("api_v1."):
            continue
        view = app.view_functions[rule.endpoint]
        perms = getattr(view, "ops_permissions", None)
        any_of = getattr(view, "ops_permissions_any_of", False)
        if perms is None:
            gate = "public" if rule.endpoint.endswith(("login", "logout", "forgot_password", "reset_password", "reset_password_status", "download_attachment")) else "login"
        elif not perms:
            gate = "any member"
        else:
            gate = (" or " if any_of else " and ").join(f"`{p}`" for p in perms)
        methods = ",".join(sorted(m for m in rule.methods if m not in {"HEAD", "OPTIONS"}))
        doc = (view.__doc__ or "").strip().splitlines()
        summary = doc[0] if doc else ""
        rows.append((rule.rule, methods, gate, summary))
    rows.sort()
    lines = [
        "# ASME Ops API reference (`/api/v1`)",
        "",
        "Generated by `python scripts/generate_ops_docs.py`. Envelope: success `{\"ok\": true, \"payload\": ...}`; errors `{\"ok\": false, \"code\", \"error\", ...}` with `code=\"validation\"` carrying `errors: {field: message}`. Mutations must send `Content-Type: application/json` (multipart uploads send `X-Requested-With: ASME-Ops`). Lists accept `limit`, `cursor`, `sort`, `q` and `filter[name]=a,b`; they return `{items, next_cursor, total}`. Ids are UUID strings except legacy user ids, which are integers.",
        "",
        "| Method | Path | Requires | Notes |",
        "|---|---|---|---|",
    ]
    for path, methods, gate, summary in rows:
        lines.append(f"| {methods} | `{path}` | {gate} | {summary} |")
    lines += [
        "",
        "## Authentication",
        "",
        "`POST /api/v1/auth/login` `{identifier, password}` starts the session cookie; `GET /api/v1/session` returns the user, organization, membership role, permission map, scope ids, setup state and feature flags. A user without an active membership receives `403 no_membership`.",
        "",
        "Account flows: `POST /api/v1/auth/forgot-password` `{email}` always answers `{sent: true}` for a well-formed address and queues an `auth.password_reset` job; the worker e-mails a link of the form `<ASME_PUBLIC_BASE_URL>/app/auth/reset-password#token=<token>` (the request host is used only outside production). `POST /api/v1/auth/reset-password/status` `{token}` reports `{valid, purpose: invite|reset, email (masked), expires_at}` or `404 invalid_token`; `POST /api/v1/auth/reset-password` `{token, password, confirm_password}` sets the password once. Signed-in users change their password with `POST /api/v1/auth/change-password` and edit `name`, `major`, `graduation_year` and `phone` with `PATCH /api/v1/session/profile`. These endpoints answer `429 rate_limited` with `retry_after` when limited.",
        "",
        "## Change feed",
        "",
        "`GET /api/v1/changes?since=<ISO-8601>` returns audit events the caller may read, oldest first, plus `now` and the unread notification count. Clients poll it every `features.poll_seconds` and revalidate the affected queries.",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    app = create_app(auto_migrate=False, outbox_worker_enabled=False)
    (ROOT / "docs" / "permissions-matrix.md").write_text(permissions_matrix(), encoding="utf-8")
    with app.app_context():
        (ROOT / "docs" / "api.md").write_text(api_reference(app), encoding="utf-8")
    print("wrote docs/permissions-matrix.md and docs/api.md")
