"""ORM models for the ``ops_*`` tables. Import this package (it is imported by
``asme.models``) so ``db.create_all`` and Alembic see every table."""

from asme.ops.models.identity import Membership, Organization, Permission, Role, RolePermission, Sequence, UserPreference
from asme.ops.models.inventory import (
    InventoryBalance,
    InventoryTransaction,
    Part,
    PartAsset,
    PartType,
    PartVendor,
    PurchaseRequest,
    PurchaseRequestEvent,
    PurchaseRequestItem,
    WorkOrderPart,
)
from asme.ops.models.projects import Milestone, OpsProject, ProjectMember
from asme.ops.models.shared import Attachment, AuditEvent, Comment, Notification, SavedFilter
from asme.ops.models.structure import Asset, AssetStatusHistory, AssetType, AssetTypeLink, Category, Location, Team, TeamMember, Vendor
from asme.ops.models.work import (
    CostEntry,
    TimeEntry,
    WorkOrder,
    WorkOrderAsset,
    WorkOrderAssignee,
    WorkOrderCategory,
    WorkOrderDependency,
    WorkOrderStatusHistory,
    WorkOrderWatcher,
)

__all__ = [
    "Asset",
    "AssetStatusHistory",
    "AssetType",
    "AssetTypeLink",
    "Attachment",
    "AuditEvent",
    "Category",
    "Comment",
    "CostEntry",
    "InventoryBalance",
    "InventoryTransaction",
    "Location",
    "Membership",
    "Milestone",
    "Notification",
    "OpsProject",
    "Organization",
    "Part",
    "PartAsset",
    "PartType",
    "PartVendor",
    "Permission",
    "ProjectMember",
    "PurchaseRequest",
    "PurchaseRequestEvent",
    "PurchaseRequestItem",
    "Role",
    "RolePermission",
    "SavedFilter",
    "Sequence",
    "Team",
    "TeamMember",
    "TimeEntry",
    "UserPreference",
    "Vendor",
    "WorkOrder",
    "WorkOrderAsset",
    "WorkOrderAssignee",
    "WorkOrderCategory",
    "WorkOrderDependency",
    "WorkOrderPart",
    "WorkOrderStatusHistory",
    "WorkOrderWatcher",
]
